# Generated by Django 6.0.6 on 2026-06-13 10:40

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=files.models.File.get_file_upload_path),
        ),
    ]
