# Generated by Django 6.0.6 on 2026-06-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_user_folder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='users/'),
        ),
    ]
